# Generated by Django 3.2.5 on 2021-08-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='contact_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='pin_code',
            field=models.IntegerField(default=0),
        ),
    ]
