# Generated by Django 3.2.5 on 2021-08-02 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodApp', '0002_auto_20210802_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='pin_code',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256)),
                ('contact_no', models.IntegerField()),
                ('pin_code', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
