# Generated by Django 3.2.5 on 2021-08-03 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0002_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='ordered_date',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='status',
        ),
    ]
