# Generated by Django 3.2.5 on 2021-08-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodApp', '0003_auto_20210803_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
